myproject/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from django.conf import settings 
from . import views
# from django.conf.urls.static import static
from django.views.static import serve


urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('',views.homepage),
    path('about/',views.aboutpage),
    path('posts/', include('posts.urls')), # posts/urls.py
    path('users/', include('users.urls')), # users/urls.py
    path('todos/', include('todos.urls')),
]

# urlpatterns += static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)
# if settings.DEBUG404:
#     urlpatterns += urlpatterns('',(r'^static/(?P<path>.*)$', 'django.views.static.serve',
#          {'document_root': os.path.join(os.path.dirname(__file__), 'static')} ),
#     )

posts/urls.py
from django.urls import path
from . import views
#/posts
app_name='posts'
# designated name for posts module


urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', views.posts_list, name='list'), # posts:list
    path('new-post/',views.post_new,name='new-post'),
    path('<slug:slug>', views.post_page, name='page'), #posts:page
]

templates/about.html
{% extends 'layout.html' %}
{% block title %}
Home
{% endblock %}

{% block content %}
<h1>About Page</h1>
  <p>Check out my <a href="/">home</a> page</p>
{% endblock %}

templates/home.html
{% extends 'layout.html' %}
{% block title %}
Home
{% endblock %}

{% block content %}
<h1 class='text-red-500'>Home Page</h1>
<p>Check out my <a href="/about">about</a> page</p>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
{% comment %} {% load partials %} {% endcomment %}

<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    {% block title %}
    Django Blog
    {% endblock %}
  </title>
  {% comment %} <link rel="stylesheet" href="{% static 'css/styles.css' %}" /> {% endcomment %}
  <link href="https://cdn.jsdelivr.net/npm/daisyui@4.12.10/dist/full.min.css" rel="stylesheet" type="text/css" />
  
  <script src="https://cdn.tailwindcss.com?plugins=typography"></script>
  <script src="https://unpkg.com/htmx.org@2.0.0" integrity="sha384-wS5l5IKJBvK6sPTKa2WZ1js3d947pvWXbPJ1OmWfEuxLgeHcEbjUUA5i9V5ZkpCw" crossorigin="anonymous"></script>
</head>
<body hx-headers='{"X-CSRFToken":"{{csrf_token}}"}'>
  <nav class="flex justify-center space-x-8 items-center py-4 bg-teal-800">
    <a href="/">
      <span role='img' aria-label="Home" title="Home">
        🏠
      </span>  
    </a> 
    <a href="/about">
      <span role='img' aria-label="About"title="About">
        😀
      </span>
    </a> 
    <a href="{% url 'posts:list' %}">
      <span role='img' aria-label="Posts" title="Posts">
        📰
      </span>
    </a> 
    {% comment %} <button class="btn btn-active btn-link">Link</button> {% endcomment %}
    {%if user.is_authenticated %}
    <a href="{% url 'posts:new-post' %}">
      <span role='img' aria-label="Posts" title="New Post">
        🆕New Post
      </span>
    </a> 
    <a href="{% url 'todos:todo_list' %}">
      <span role='img' aria-label="Todos" title="Todos">
        Todo
      </span>
    </a> 

    <form class="logout" action="{% url 'users:logout' %}" method="post">
      {% csrf_token %}
      <button class="logout-button" role='img' aria-label="User Logout" title="User Logout">
        👋Logout
      </button>
    </form>
    {% else %}

    <a href="{% url 'users:register' %}">
      <span role="img" aria-label="User Registration" title="User Registration">🚀Register</span>
    </a> 
    <a href="{% url 'users:login' %}">
      <span role="img" aria-label="User Login" title="User Login">🔏Login</span>
    </a>

    {% endif %}
    {% comment %} <a href="/posts">📰</a> | {% endcomment %}
  </nav>
  
  <main class="px-12 bg-teal-800 min-h-screen">
    {% block content %}
    {% endblock %}
  </main>
  
</body>
</html>