myproject/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from django.conf import settings 
from . import views
# from django.conf.urls.static import static
from django.views.static import serve


urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('',views.homepage),
    path('about/',views.aboutpage),
    path('posts/', include('posts.urls')), # posts/urls.py
    path('users/', include('users.urls')), # users/urls.py
    path('todos/', include('todos.urls')),
]

# urlpatterns += static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)
# if settings.DEBUG404:
#     urlpatterns += urlpatterns('',(r'^static/(?P<path>.*)$', 'django.views.static.serve',
#          {'document_root': os.path.join(os.path.dirname(__file__), 'static')} ),
#     )

posts/urls.py
from django.urls import path
from . import views
#/posts
app_name='posts'
# designated name for posts module


urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', views.posts_list, name='list'), # posts:list
    path('new-post/',views.post_new,name='new-post'),
    path('<slug:slug>', views.post_page, name='page'), #posts:page
]

todos/urls.py
from django.urls import path
from . import views
#/posts
app_name='todos'
# designated name for posts module


urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', views.todos, name='todo_list'), # todos:todo_list
    path('submit-todo/', views.submit_todo, name='submit_todo'), # todos:submit_todo
    path('create-todo/',views.create_todo, name='create_todo'),
    path('completed-todo/<int:pk>/', views.completed_todo, name='completed_todo'), # todos:submit_todo
    path('delete_todo/<int:pk>/', views.delete_todo, name='delete_todo'), # todos:submit_todo
    path('update_todo/<int:pk>/', views.update_todo, name='update_todo'), # todos:submit_todo
]

todos/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Todo(models.Model):
  description = models.CharField(max_length=200)
  is_completed = models.BooleanField(default=False)
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  created_at = models.DateTimeField(auto_now_add=True)
  
  def __str__(self):
    return self.description
  

todos/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_http_methods
from django_htmx.http import retarget


from todos.models import Todo
from todos.froms import TodoForm
# Create your views here
@login_required(login_url="/users/login/")
def todos(request):
  context = {'todos': Todo.objects.filter(user=request.user),'user':request.user}
  if request.htmx:
    # print("htmx??? ",request.htmx)
    return render(request,'todos/partials/todos-container.html',context)
   
  return render(request, 'todos/todos.html', context)

@login_required(login_url='/users/login')
@require_POST
def submit_todo(request):
  form = TodoForm(request.POST)
  print("Todo from form.is_valid::",form.is_valid())
  if form.is_valid():
    todo=form.save(commit=False)
    print("Todo from the form::",todo)
    todo.user= request.user
    print('usser',request.user)
    todo.save()
    # return html
    context={'todo': todo}
    return render(request, 'todos/todos.html#todoitem-partial',context)
    
@login_required(login_url='/users/login')
@require_POST
def completed_todo(request, pk):
  todo = get_object_or_404(Todo, pk=pk, user=request.user)
  todo.is_completed = True
  print("saving todo ::",todo)
  todo.save()
  print("saved todo ::",todo)
  context= {'todo': todo}
  return render(request, 'todos/partials/todos-container.html#todoitem-partial',context)
    

@login_required(login_url='/users/login')
@require_http_methods(['DELETE'])
def delete_todo(request, pk):
  todo = get_object_or_404(Todo,pk=pk, user=request.user)
  todo.delete()
  
  response = HttpResponse(status=204)
  response['HX-Trigger'] = 'delete-trigger'
  return response   

@login_required(login_url='/users/login')
def update_todo(request, pk):
  todo = get_object_or_404(Todo, pk=pk, user=request.user)
  if request.method == 'POST':
    form = TodoForm(request.POST, instance=todo)
    if form.is_valid():
      todo = form.save()
      context = {'message': "Todo was updated successfully!"}
      return render(request, 'todos/partials/todo-success.html', context)
    else:
      context = {
          'form': form,
          'todo': todo,
      }
      response = render(request, 'todos/partials/update-todo.html', context)
      return retarget(response, '#todos-block')
  context= {
    'form': TodoForm(instance=todo),
    'todo': todo
  }
  return render(request, 'todos/partials/update-todo.html', context)

  
@login_required(login_url='/users/login')
def create_todo(request):
  if request.method=='POST':
    form = TodoForm(request.POST)
    if form.is_valid():
      todo=form.save(commit=False)
      todo.user= request.user
      todo.save()
      context= {'message': "Todo was added successfully"}
      return render(request, 'todos/partials/todo-success.html',context)
    else:
      context ={'form': form}
      response = render(request, 'todos/partials/create-todo.html',context)
      return retarget(response, '#todos-block')
  context = {'form': TodoForm()}  
  return render(request, 'todos/partials/create-todo.html', context) 

todos/templates/todos/partials/create-todo.html
{% load widget_tweaks %}
<div id="create-todo" class="px-4 py-4">
  <h1 class='text-xl'>Create New Todo</h1>
  
  <form class="mb-4" hx-post="{% url 'todos:create_todo' %}">
   
    {% comment %} {{form.as_p}} {% endcomment %}
      {% comment %} <div class='form-control'>
        <label class="mb-2">Task Description</label>
        {% render_field form.description class="input input-bordered" %}
      </div>
      <div class='form-control'>
        <label class="mb-2">Is Completed</label>
        {% render_field form.is_completed class="checkbox checkbox-success" %}
      </div> {% endcomment %}

    {% include 'todos/partials/todo-form.html' %}
    
    
    <button type="submit" class="mt-2 btn btn-primary">Add todo</button>
  </form>
</div>

todos/templates/todos/partials/todo-form.html
{% load widget_tweaks %}
{% comment %} {{form.as_p}} {% endcomment %}
<div class=w-full>

  <div class='form-control mb-2'>
    {% comment %} <label class="mb-2">Task Description</label> {% endcomment %}
    {{ form.description|add_label_class:"lable text-teal-800"}}
    {% render_field form.description class="input input-bordered" %}
  </div>
  <div class='form-control'>
    {% comment %} <label class="mb-2">Is Completed</label> {% endcomment %}
    {{ form.is_completed|add_label_class:"lable text-teal-800"}}
    {% render_field form.is_completed class="checkbox checkbox-success" %}
  </div>
</div>

todos/templates/todos/partials/todo-success.html
<div role="alert" class="alert alert-info">
  <svg
    xmlns="http://www.w3.org/2000/svg"
    class="h-6 w-6 shrink-0 stroke-current"
    fill="none"
    viewBox="0 0 24 24">
    <path
      stroke-linecap="round"
      stroke-linejoin="round"
      stroke-width="2"
      d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
  </svg>
  <span>{{message}}!</span>
</div>
<div class='mt-4'>
  <button class= 'btn btn-success'
    hx-get="{% url 'todos:create_todo' %}"
    hx-target="#todos-block">
    Add Another
  </button>
  <button class='btn btn-success'
    hx-get="{% url 'todos:todo_list' %}"
    hx-push-url = 'true'
    hx-target="#todos-block"
  >
    Back to Todo List
  </button>
</div>

todos/templates/todos/partials/todos-container.html
{% load partials %}
{% comment %} {% load widget-tweaks %} {% endcomment %}
<div id='todos-container' class='w-full'>
  <div class="flex justify-center space-x-4 bg-teal-800 items-center border-b border-teal-600">
              
    <h1 class="prose-2xl  p-2">
      <span class="text-white">
      {{user.username}} 's
    </span>
     Todos Page</h1>
    
    <a 
      hx-get="{% url 'todos:create_todo' %}"
      hx-push-url="true"
      hx-target="#todos-block"
      class="cursor-pointer">
        <svg xmlns="http://www.w3.org/2000/svg" fill="green" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-10 h-10 text-white">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v6m3-3H9m12 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
        </svg>
      </a>
  </div>

  <table class="table table-zebra table-lg bg-slate-200">
    <thead class='bg-gray-400'>
      <tr>
        <th>Description</th>
        <th>Created</th>
        <th>Completed</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody id="todo-table-body">
      {% for todo in todos %}
      {% partialdef todoitem-partial inline=True %}
      <tr>
        <td>{{ todo.description }}</td>
        <td>{{ todo.created_at }}</td>
        <td>{{ todo.is_completed }}</td>
        <td class="flex justify-center items-center">
          {% if not todo.is_completed%}
          <button class="btn btn-success btn-xs"
            hx-post="{% url 'todos:completed_todo' todo.pk %}"
            hx-target="closest tr"
            hx-swap='outerHTML'
          >
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6 text-white">
              <path stroke-linecap="round" stroke-linejoin="round" d="m4.5 12.75 6 6 9-13.5" />
            </svg>
          </button>
          {% endif %}
        <button 
          hx-delete="{% url 'todos:delete_todo' todo.pk %}"
          hx-on:delete-trigger="this.closest('tr').remove()" 
          class="btn btn-error btn-xs">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
          </svg>
        </button>
        {% comment %} Edit {% endcomment %}
        
        <a class="hover:cursor-pointer" 
          hx-get="{% url 'todos:update_todo' todo.pk %}"
          hx-push-url = "true"
          hx-target="#todos-block"
          >
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L6.832 19.82a4.5 4.5 0 0 1-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 0 1 1.13-1.897L16.863 4.487Zm0 0L19.5 7.125" />
          </svg>
        </a>
              
        </td>
      </tr>
        {% endpartialdef %}
        {% endfor %}
    </tbody>
  </table>
  <p class="mt-4 px-2 py-2 bg-teal-200 text-center">Go Back to my <a class="btn btn-ghost" href="/">home</a> page</p>
</div>

todos/templates/todos/partials/update-todo.html
{% load widget_tweaks %}


<div>
  <h1 class='text-xl'>Update Todo</h1>
  <form class="mb-4" 
      hx-post="{% url 'todos:update_todo' todo.pk %}">

      {% include 'todos/partials/todo-form.html' %}


      <button class="mt-2 btn btn-success">Update Todo</button>
      <button class="mt-2 btn btn-success"
        hx-get="{% url 'todos:todo_list' %}"
        hx-target="#todos:block"
        hx-push-url="/todos"
      >cancel</button>
    </form>